[package]
name = "comms"
version = "0.1.0"
edition = "2021"

[features]
default = []
ground-station = []
cubesat = []

[target.'cfg(feature = "ground-station")'.lib]
name = "comms"
path = "src/lib.rs"
crate-type = ["cdylib"]

[target.'cfg(feature = "ground-station")'.dependencies]
pyo3 = "0.22.0"

[[bin]]
name = "cubesat"
path = "src/lib.rs"

[target.'cfg(feature = "cubesat")'.bin]
name = "cubesat"
path = "src/lib.rs"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
