[package]
name = "comms"
version = "0.1.0"
edition = "2021"

[features]
default = []
ground-station = []
cubesat = []

[lib]
name = "comms"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "cubesat"
path = "src/main.rs"
required-features = ["cubesat"]

[target.'cfg(feature = "ground-station")'.dependencies]
pyo3 = "0.22.0"


[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(ground_station)'] }